version: '2'
services:
  elasticsearch:
#    image: elasticsearch:2.4
    build:
      context: ./elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearchdata/2:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - americanoutlets-network
