#!/usr/bin/env bash
service apache2 stop
sleep 1
docker-compose up
docker-compose -f docker-compose.yml ps

echo "
===================== 🚀 Done 🚀 ===================

      Created by Me
      v.1
      Access your new links:

      🌎 Web server: http://americanoutlets.local
      🌎 ADMIN:      http://americanoutlets.local/xmng
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================="
