#!/usr/bin/env bash

docker-compose -f docker-compose.yml -f docker-compose.elasticsearch.yml up -d
docker-compose -f docker-compose.yml -f docker-compose.elasticsearch.yml ps

echo "
===================== 🚀 Done 🚀 ===================

      Created by Me
      v.1
      Access your new links:

      🌎 Web server: http://americanoutlets.local or http://localhost
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================="
